"""create containment tables

Revision ID: 0001
Revises:
Create Date: 2026-08-21 23:27:58.849548

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_commands',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('cluster_id', sa.String(length=64), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('pod_name', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_response_commands_cluster_id'), 'response_commands', ['cluster_id'], unique=False)
    op.create_table('response_rules',
    sa.Column('rule_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('rule_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_rules')
    op.drop_index(op.f('ix_response_commands_cluster_id'), table_name='response_commands')
    op.drop_table('response_commands')
    # ### end Alembic commands ###
